In [1]:
import numpy as np

def convolution2d(image, kernel):
    m, n = kernel.shape
    if (m == n):
        y, x = image.shape
        y = y - m + 1
        x = x - m + 1
        new_image = np.zeros((y,x))
        for i in range(y):
            for j in range(x):
                new_image[i][j] = np.sum(image[i:i+m, j:j+m]*kernel)
    return new_image

kernel = np.array([[-1, -1, -1], [-1, 8, -1], [-1, -1, -1]])

image=np.array([[1, 1, 0, 1], [0, 1, 0, 1], [1, 1, 1, 0], [1, 1, 0 , 0]])


convolution2d(image,kernel)

array([[ 3., -6.],
       [ 3.,  4.]])

In [2]:
image

array([[1, 1, 0, 1],
       [0, 1, 0, 1],
       [1, 1, 1, 0],
       [1, 1, 0, 0]])

In [3]:
kernel

array([[-1, -1, -1],
       [-1,  8, -1],
       [-1, -1, -1]])